org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=1.20.4
  yarn_mappings=1.20.4+build.1
  loader_version=0.15.3
  fabric_version=0.93.1+1.20.4

# Mod Properties
  group=moriz
  displayname=orangesunshine
  authors=moriz, TripleHeadedSheep
  description=Adds drugs into Minecraft.

# Dependencies
  fabwork_version=1.3.0+1.20.2
  kirin_version=1.17.0+1.20.4
  modmenu_version=9.0.0-pre.1
  terraformer_api_version=8.0.0

# TMI Testing
emi_version=1.0.29+1.20.4

# JEI
mc_version=1.20.4
jei_version=17.0.0.30