modLoader="javafml"
loaderVersion="${loader_range}"
license="All rights reserved"

[[mods]]
modId = "orangesunshine"
version = "${file.jarVersion}"
displayName = "Orange Sunshine"
authors = "Moriz"
description = '''
Minecraft Drugmod
'''
logoFile = "logo.png"

[[dependencies.OrangeSunshine]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.OrangeSunshine]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${mc_range}"
    ordering = "NONE"
    side = "BOTH"
