/*
 *  Copyright (c) 2014, Lukas Tenbrink.
 *  * http://lukas.axxim.net
 */

// Date: 8-4-2013 14:29:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package moriz.orangesunshine.client.render;

import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartNames;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.client.renderer.rendertype.RenderType;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.resources.Identifier;

import java.util.function.Function;

public class RastaHeadModel extends Model {
    private final ModelPart root;

    public RastaHeadModel() {
        super(LayerDefinition.create(getMeshDefinition(CubeDeformation.NONE), 128, 64).bakeRoot(), (Function<Identifier, RenderType>) RenderTypes::entityTranslucent);
        this.root = this.root();
    }

    public static MeshDefinition getMeshDefinition(CubeDeformation dilation) {
        MeshDefinition data = new MeshDefinition();
        PartDefinition root = data.getRoot();
        PartDefinition head = root.addOrReplaceChild(PartNames.HEAD, CubeListBuilder.create()
                .texOffs(0, 0).addBox(-4, -8, -4, 8, 8, 8, dilation).mirror(), PartPose.ZERO);
        head.addOrReplaceChild("nose", CubeListBuilder.create()
                .texOffs(33, 0).addBox(-0.5F, -4.8F, -5F, 1, 2, 1, dilation).mirror(), PartPose.offsetAndRotation(0, 0, 0, -0.0743572F, 0, 0));
        head.addOrReplaceChild("nostrils", CubeListBuilder.create()
                .texOffs(38, 0).addBox(-1F, -4.2F, -4.5F, 2, 1, 1, dilation).mirror(), PartPose.ZERO);
        head.addOrReplaceChild("hair", CubeListBuilder.create()
                .texOffs(0, 17).addBox(-4.5F, -7.5F, -4.5F, 9, 11, 9, dilation).mirror(), PartPose.ZERO);
        root.addOrReplaceChild(PartNames.HAT, CubeListBuilder.create()
                .texOffs(0, 38).addBox(-5F, -10F, -8.5F, 10, 7, 12, dilation).mirror(), PartPose.offsetAndRotation(0, 0, 0, -0.669215F, 0, 0));
        root.addOrReplaceChild("joint", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-0.5F, -3.5F, -5F, 1, 1, 2, dilation).mirror(), PartPose.offsetAndRotation(0, 0, 0, 0.4089647F, -0.2602503F, 0));
        return data;
    }

}
